apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  description: Service for handling payments and fund confirmation
spec:
  type: service
  lifecycle: production
  owner: payments-team
  system: Payments
  consumesApis:
    - funds_confirmation_api
  providesApis:
    - payment_initiation_api
  dependsOn:
    - accounts_service
