apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  description: Service for handling payments and fund confirmation
  appID: app-2
  tags: 
    - java
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/backstage-poc/account-info-api/main/.spectral.yaml
spec:
  type: service
  lifecycle: production
  owner: payments-team
  system: Payments
  consumesApis:
    - funds_confirmation_api
  providesApis:
    - payment_initiation_api

